// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBckWfRIOYJ2qnC6wUWRsKIKQkx3pEUi84',
    appId: '1:747896887728:web:ed41195d4c6fe8a45c1e75',
    messagingSenderId: '747896887728',
    projectId: 'bragging-rights-ea6e1',
    authDomain: 'bragging-rights-ea6e1.firebaseapp.com',
    storageBucket: 'bragging-rights-ea6e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD76BPNxjmV2h6k6s8MXZs-sOemcacQkww',
    appId: '1:747896887728:android:960c93fd20ff88075c1e75',
    messagingSenderId: '747896887728',
    projectId: 'bragging-rights-ea6e1',
    storageBucket: 'bragging-rights-ea6e1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBckWfRIOYJ2qnC6wUWRsKIKQkx3pEUi84',
    appId: '1:747896887728:web:00e2291ce4dd20f85c1e75',
    messagingSenderId: '747896887728',
    projectId: 'bragging-rights-ea6e1',
    authDomain: 'bragging-rights-ea6e1.firebaseapp.com',
    storageBucket: 'bragging-rights-ea6e1.firebasestorage.app',
  );
}
